comment_width = 140
format_code_in_doc_comments = true
format_strings = true
max_width = 100
merge_imports = true
newline_style = "Unix"
normalize_comments = true
reorder_modules = true
use_field_init_shorthand = true
wrap_comments = true
