[package]
name = "steam-language-gen"
version = "0.1.0"
authors = ["Martin <martin@hotmail.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0.1"
petgraph = "0.4.13"

[dependencies.Inflector]
version = "*"
default-features = false
